

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ING-JUANMATA
 */
public class Programa extends javax.swing.JFrame {

    private Matriz datos;

    /**
     * Creates new form Programa
     */
    public Programa() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private void mostrar(int[][] data) {
        String mat = "";
        int tam = data.length;
        for (int i = 0; i < tam; i++) {
            for (int j = 0; j < tam; j++) {
                mat += j == tam - 1 ? data[i][j] + "\n" : data[i][j] + ", ";
            }
        }

        txtArea.setText(mat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTam = new javax.swing.JTextField();
        btnVerMat = new javax.swing.JButton();
        btnGen = new javax.swing.JButton();
        btnDiagonal = new javax.swing.JButton();
        btnDInv = new javax.swing.JButton();
        btnSuperior = new javax.swing.JButton();
        btnInferior = new javax.swing.JButton();
        btnSuperiorI = new javax.swing.JButton();
        btnInferiorI = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MATRIZ TRIANGULAR");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tamaño");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtTam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtTam, gridBagConstraints);

        btnVerMat.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnVerMat.setText("Ver Matriz");
        btnVerMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMatActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnVerMat, gridBagConstraints);

        btnGen.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnGen.setText("Crear Matriz");
        btnGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnGen, gridBagConstraints);

        btnDiagonal.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnDiagonal.setText("Diagonal");
        btnDiagonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagonalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnDiagonal, gridBagConstraints);

        btnDInv.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnDInv.setText("D Inversa");
        btnDInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDInvActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnDInv, gridBagConstraints);

        btnSuperior.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSuperior.setText("T Superior");
        btnSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuperiorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnSuperior, gridBagConstraints);

        btnInferior.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnInferior.setText("T Inferior");
        btnInferior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInferiorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnInferior, gridBagConstraints);

        btnSuperiorI.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSuperiorI.setText("T  S Inversa");
        btnSuperiorI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuperiorIActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnSuperiorI, gridBagConstraints);

        btnInferiorI.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnInferiorI.setText("T I Inversa");
        btnInferiorI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInferiorIActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnInferiorI, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenActionPerformed
        datos = new Matriz(Integer.parseInt(txtTam.getText()));
        mostrar(datos.getDatos());
    }//GEN-LAST:event_btnGenActionPerformed

    private void btnVerMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMatActionPerformed
        mostrar(datos.getDatos());
    }//GEN-LAST:event_btnVerMatActionPerformed

    private void btnDiagonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagonalActionPerformed
        String mat = "";
        int[] vals = datos.obtenerDiagonal();

        for (int i = 0; i < vals.length; i++) {
            mat += vals[i] + (i == vals.length - 1 ? "" : ", ");
        }

        txtArea.setText(mat);
    }//GEN-LAST:event_btnDiagonalActionPerformed

    private void btnDInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDInvActionPerformed
        String mat = "";
        int[] vals = datos.obtenerDiagonalInvertida();

        for (int i = 0; i < vals.length; i++) {
            mat += vals[i] + (i == vals.length - 1 ? "" : ", ");
        }

        txtArea.setText(mat);
    }//GEN-LAST:event_btnDInvActionPerformed

    private void btnSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuperiorActionPerformed
        mostrar(datos.obtenerTriangularSuperior());
    }//GEN-LAST:event_btnSuperiorActionPerformed

    private void btnInferiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInferiorActionPerformed
        mostrar(datos.obtenerTriangularInferior());
    }//GEN-LAST:event_btnInferiorActionPerformed

    private void btnSuperiorIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuperiorIActionPerformed
        mostrar(datos.obtenerTriangularSuperiorInversa());
    }//GEN-LAST:event_btnSuperiorIActionPerformed

    private void btnInferiorIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInferiorIActionPerformed
        mostrar(datos.obtenerTriangularInferiorInversa());
    }//GEN-LAST:event_btnInferiorIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDInv;
    private javax.swing.JButton btnDiagonal;
    private javax.swing.JButton btnGen;
    private javax.swing.JButton btnInferior;
    private javax.swing.JButton btnInferiorI;
    private javax.swing.JButton btnSuperior;
    private javax.swing.JButton btnSuperiorI;
    private javax.swing.JButton btnVerMat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtTam;
    // End of variables declaration//GEN-END:variables
}
